jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Ens\JobeetBundle\Entity\User: sha512
        #Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
          entity: { class: Ens\JobeetBundle\Entity\User, property: username }
        #in_memory:
        #    memory:
        #        users:
        #            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            anonymous: ~
            logout:
                path:   /logout
                target: /

    access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }
        
