Ens\JobeetBundle\Entity\Job:
    properties:
      description:
          - NotBlank: ~
      category:
          - NotBlank: ~
      type:
          - NotBlank: ~
          - Choice: { callback: getTypeValues }
      company:
          - NotBlank: ~
      position:
          - NotBlank: ~
      location:
          - NotBlank: ~      
      how_to_apply:
          - NotBlank: ~
      email:
          - NotBlank: ~
          - Email: ~
      file:
          - Image: ~